// ---
// build.ts — validates skills, bundles cross-harness CLI bins (#97)
// Toolchain: bun (Bun.build). Output targets plain node ≥ 18 — installers of the
// published tarball never need bun; only this build step does.
// ---
import * as fs from "node:fs";
import * as path from "node:path";

// ---
// SKILL.md VALIDATION (ported unchanged from the retired esbuild build.mjs)
// ---

function findSkillFiles(dir: string): string[] {
  let results: string[] = [];
  const list = fs.readdirSync(dir);
  for (const file of list) {
    if (file === "node_modules" || file === ".git") continue;
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(findSkillFiles(filePath));
    } else if (file === "SKILL.md") {
      results.push(filePath);
    }
  }
  return results;
}

function validateSkills(): void {
  console.log("🔍 Validating SKILL.md files...");
  const skillFiles = findSkillFiles(process.cwd());
  let errors = 0;

  for (const filePath of skillFiles) {
    const content = fs.readFileSync(filePath, "utf8");
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match) {
      console.error(`❌ [Skill Format Error] ${filePath}: No frontmatter found.`);
      errors++;
      continue;
    }

    const frontmatter = match[1];
    const nameMatch = frontmatter.match(/^name:\s*(.+)$/m);
    if (!nameMatch) {
      console.error(`❌ [Skill Format Error] ${filePath}: 'name' field is missing in frontmatter.`);
      errors++;
      continue;
    }

    const name = nameMatch[1].trim();
    const validNameRegex = /^[a-z0-9-]+$/;
    if (!validNameRegex.test(name)) {
      console.error(`❌ [Skill Format Error] ${filePath}: name "${name}" contains invalid characters (must be lowercase a-z, 0-9, hyphens only).`);
      errors++;
    }
  }

  if (errors > 0) {
    throw new Error(`${errors} skill validation error(s) found.`);
  }
  console.log(`✅ Validated ${skillFiles.length} SKILL.md file(s).`);
}

// ---
// CLI BUNDLING
// ---

// Generated artifacts are gitignored (see .gitignore + docs/bun-build-migration-spec.md);
// the banner is the in-file defense against agents editing build output.
function bannerFor(name: string): string {
  return (
    `// ⚠️ GENERATED by build.ts from bin/${name}.ts — DO NOT EDIT.\n` +
    `// Edits are overwritten on every build/prepare. Edit the .ts source instead.\n`
  );
}

interface BuildTarget {
  name: string;
  external: string[];
}

const TARGETS: BuildTarget[] = [
  // run-live-server stays external: it is loaded at runtime relative to the installed
  // package layout, not bundled (same as the esbuild config it replaces).
  { name: "serve", external: ["../extensions/lib/serve/run-live-server.js"] },
  { name: "wtft", external: [] },
  { name: "merge", external: [] },
  { name: "wtft-daemon", external: [] },
  // yada was a raw .ts bin (needs node ≥ 22.6 type-stripping — unsafe from a global
  // install, #31); building it closes that gap. `dedupwcount` aliases this artifact.
  { name: "yada", external: [] },
];

async function buildAll(): Promise<void> {
  validateSkills();

  console.log("🛠️  Building cross-harness CLI binaries (Bun.build)...");

  for (const t of TARGETS) {
    const result = await Bun.build({
      entrypoints: [`bin/${t.name}.ts`],
      outdir: "bin",
      naming: "[name].mjs",
      target: "node",
      format: "esm",
      external: t.external,
    });
    if (!result.success) {
      for (const log of result.logs) console.error(log);
      throw new Error(`Bundle failed for bin/${t.name}.ts`);
    }

    const outfile = `bin/${t.name}.mjs`;
    let code = fs.readFileSync(outfile, "utf8");
    code = code.replace(/^#!.*\r?\n/, "");
    code = `#!/usr/bin/env node\n${bannerFor(t.name)}${code}`;
    fs.writeFileSync(outfile, code);
    fs.chmodSync(outfile, 0o755);
    console.log(`✅ ${outfile} compiled.`);
  }
}

buildAll().catch((err) => {
  console.error("❌ Build failed:", err);
  process.exit(1);
});
