// ---
// build.ts — validates skills, bundles cross-harness CLI bins (#97)
// Toolchain: bun (Bun.build). Output targets plain node ≥ 18 — installers of the
// published tarball never need bun; only this build step does.
// ---
import * as fs from "node:fs";
import * as path from "node:path";

// ---
// SKILL.md VALIDATION (ported unchanged from the retired esbuild build.mjs)
// ---

function findSkillFiles(dir: string): string[] {
  let results: string[] = [];
  const list = fs.readdirSync(dir);
  for (const file of list) {
    if (file === "node_modules" || file === ".git") continue;
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(findSkillFiles(filePath));
    } else if (file === "SKILL.md") {
      results.push(filePath);
    }
  }
  return results;
}

function validateSkills(): void {
  console.log("🔍 Validating SKILL.md files...");
  const skillFiles = findSkillFiles(process.cwd());
  let errors = 0;

  for (const filePath of skillFiles) {
    const content = fs.readFileSync(filePath, "utf8");
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match) {
      console.error(`❌ [Skill Format Error] ${filePath}: No frontmatter found.`);
      errors++;
      continue;
    }

    const frontmatter = match[1];
    const nameMatch = frontmatter.match(/^name:\s*(.+)$/m);
    if (!nameMatch) {
      console.error(`❌ [Skill Format Error] ${filePath}: 'name' field is missing in frontmatter.`);
      errors++;
      continue;
    }

    const name = nameMatch[1].trim();
    const validNameRegex = /^[a-z0-9-]+$/;
    if (!validNameRegex.test(name)) {
      console.error(`❌ [Skill Format Error] ${filePath}: name "${name}" contains invalid characters (must be lowercase a-z, 0-9, hyphens only).`);
      errors++;
    }
  }

  if (errors > 0) {
    throw new Error(`${errors} skill validation error(s) found.`);
  }
  console.log(`✅ Validated ${skillFiles.length} SKILL.md file(s).`);
}

// ---
// HARNESS REGISTRY GENERATION (#156)
// ---

// The seam's acceptance criterion is that adding a harness touches no shared
// file. That holds only if the built-in import table is derived, not hand-kept:
// this scans extensions/lib/harness/<id>/ and writes the table, so a new
// harness directory registers itself on the next build.
const HARNESS_DIR = path.join("extensions", "lib", "harness");
const GENERATED_REGISTRY = path.join(HARNESS_DIR, "builtins.generated.ts");

function generateHarnessRegistry(): void {
  const ids = fs
    .readdirSync(HARNESS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((id) =>
      fs.existsSync(path.join(HARNESS_DIR, id, "discovery.ts")) &&
      fs.existsSync(path.join(HARNESS_DIR, id, "parse.ts"))
    )
    .sort();

  if (ids.length === 0) throw new Error(`No harnesses found under ${HARNESS_DIR}/`);

  const ident = (id: string, kind: string) =>
    id.replace(/[^a-zA-Z0-9]+(.)/g, (_m, c) => c.toUpperCase()) + kind;

  const lines: string[] = [
    `// ⚠️ GENERATED by build.ts from ${HARNESS_DIR}/*/ — DO NOT EDIT.`,
    `// Regenerated on every build/prepare. Add a harness by creating`,
    `// ${HARNESS_DIR}/<id>/{discovery,parse}.ts — this table picks it up.`,
    ``,
    `import type { HarnessDiscovery, HarnessParseAdapter } from "./types.ts";`,
  ];
  for (const id of ids) {
    lines.push(`import { discovery as ${ident(id, "Discovery")} } from "./${id}/discovery.ts";`);
    lines.push(`import { parse as ${ident(id, "Parse")} } from "./${id}/parse.ts";`);
  }
  lines.push(``);
  lines.push(`/** Built-in harnesses, keyed by id (= directory name). */`);
  lines.push(
    `export const BUILTIN_HARNESSES: Record<string, { discovery: HarnessDiscovery; parse: HarnessParseAdapter }> = {`
  );
  for (const id of ids) {
    lines.push(`\t${JSON.stringify(id)}: { discovery: ${ident(id, "Discovery")}, parse: ${ident(id, "Parse")} },`);
  }
  lines.push(`};`);
  lines.push(``);

  const next = lines.join("\n");
  const prev = fs.existsSync(GENERATED_REGISTRY) ? fs.readFileSync(GENERATED_REGISTRY, "utf8") : "";
  if (prev !== next) fs.writeFileSync(GENERATED_REGISTRY, next);
  console.log(`\u2705 Harness registry: ${ids.join(", ")}`);
}

// ---
// CLI BUNDLING
// ---

// Generated artifacts are TRACKED, not gitignored (see .gitignore + #159's
// spec-159-pack-and-smoke.md) — required so `npm install` from a git URL has
// something to run without a build step. The banner is the in-file defense
// against agents editing build output by hand.
function bannerFor(name: string): string {
  return (
    `// ⚠️ GENERATED by build.ts from bin/${name}.ts — DO NOT EDIT.\n` +
    `// Edits are overwritten on every build/prepare. Edit the .ts source instead.\n`
  );
}

interface BuildTarget {
  name: string;
  external: string[];
}

const TARGETS: BuildTarget[] = [
  // run-live-server stays external: it is loaded at runtime relative to the installed
  // package layout, not bundled (same as the esbuild config it replaces).
  { name: "serve", external: ["../extensions/lib/serve/run-live-server.js"] },
  { name: "wtft", external: [] },
  { name: "merge", external: [] },
  { name: "wtft-daemon", external: [] },
  // yada was a raw .ts bin (needs node ≥ 22.6 type-stripping — unsafe from a global
  // install, #31); building it closes that gap. `dedupwcount` aliases this artifact.
  { name: "yada", external: [] },
];

async function buildAll(): Promise<void> {
  validateSkills();
  generateHarnessRegistry();

  console.log("🛠️  Building cross-harness CLI binaries (Bun.build)...");

  for (const t of TARGETS) {
    const result = await Bun.build({
      entrypoints: [`bin/${t.name}.ts`],
      outdir: "bin",
      naming: "[name].mjs",
      target: "node",
      format: "esm",
      external: t.external,
    });
    if (!result.success) {
      for (const log of result.logs) console.error(log);
      throw new Error(`Bundle failed for bin/${t.name}.ts`);
    }

    const outfile = `bin/${t.name}.mjs`;
    let code = fs.readFileSync(outfile, "utf8");
    code = code.replace(/^#!.*\r?\n/, "");
    // Worktrees (this org's standard dev layout, ~/git-projects/CLAUDE.md) symlink
    // node_modules into the main clone. Bun.build follows that symlink to the real
    // file when it stamps a bundled node_modules source with a boundary comment, so
    // the SAME .ts input produces "// ../../../<repo>/node_modules/x.js" when built
    // from a worktree vs "// node_modules/x.js" from the main clone — a difference
    // in *where you built*, not in the source. Canonicalizing here is what makes
    // `bun run build && git diff --exit-code bin/` (the #159 staleness gate) mean
    // the same thing in both places instead of flagging every worktree build stale.
    code = code.replace(/^\/\/ (?:\.\.\/|[\w.-]+\/)*node_modules\//gm, "// node_modules/");
    code = `#!/usr/bin/env node\n${bannerFor(t.name)}${code}`;
    fs.writeFileSync(outfile, code);
    fs.chmodSync(outfile, 0o755);
    console.log(`✅ ${outfile} compiled.`);
  }
}

buildAll().catch((err) => {
  console.error("❌ Build failed:", err);
  process.exit(1);
});
